[build]
command = "npm run build"
publish = "build"
node_version = "20"

# Netlify Functions
[functions]
directory = "netlify/functions"

# SPA redirect (React Router apod.)
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# API redirects
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

# Real-time events endpoint
[[redirects]]
from = "/api/events"
to = "/.netlify/functions/websocket"
status = 200

# Broadcast endpoint
[[redirects]]
from = "/api/broadcast"
to = "/.netlify/functions/websocket"
status = 200
